### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jayvdb** [mementoweb/pymemento#6]
The code uses Python 2 only urllib2, io.BytesIO for strings, and there are probably a few other problems hidden away.

**Comment by jayvdb** [comment]
pymemento.LinkTimemap.from_uri isnt covered by tests, and does have a Python 3 problem.

```
>>> res = pymemento.LinkTimemap.from_uri('http://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pymemento/LinkTimemap.py", line 190, in from_uri
    timemap = LinkTimemap._from_link_stream(parser, uri_t)
  File ".../pymemento/LinkTimemap.py", line 256, in _from_link_stream
    for link in link_stream:
  File ".../pymemento/LinkTimemap.py", line 300, in _link_stream
    for token in tokens:
  File ".../pymemento/LinkTimemap.py", line 341, in _tokenizer
    tokens = LinkTimemap.TOKENIZER_RE.findall(line)
TypeError: can't use a string pattern on a bytes-like object
```

The simple fix is to convert the line to unicode.
```
   tokens = LinkTimemap.TOKENIZER_RE.findall(str(line))
```
That will be reasonably OK for most URIs as HTTP headers are either ISO-8859-1 or USASCII, but the tokenizer doesnt stop at the end of the HTTP headers.
